pub const WORDS: &[&str] = &[
    "the", "be", "to", "of", "and", "a", "in", "that", "have", "i",
    "it", "for", "not", "on", "with", "he", "as", "you", "do", "at",
    "this", "but", "his", "by", "from", "they", "we", "say", "her", "she",
    "or", "an", "will", "my", "one", "all", "would", "there", "their", "what",
    "so", "up", "out", "if", "about", "who", "get", "which", "go", "me",
    "when", "make", "can", "like", "time", "no", "just", "him", "know", "take",
    "people", "into", "year", "your", "good", "some", "could", "them", "see", "other",
    "than", "then", "now", "look", "only", "come", "its", "over", "think", "also",
    "back", "after", "use", "two", "how", "our", "work", "first", "well", "way",
    "even", "new", "want", "because", "any", "these", "give", "day", "most", "us",
    "great", "tell", "keep", "world", "run", "long", "hand", "play", "feel", "high",
    "put", "read", "last", "never", "change", "left", "form", "own", "need", "try",
    "ask", "love", "small", "live", "part", "home", "call", "end", "still", "man",
    "place", "both", "kind", "point", "old", "big", "might", "ask", "house", "why",
    "between", "come", "world", "help", "different", "turn", "move", "high", "face",
    "number", "name", "hand", "head", "side", "let", "boy", "group", "car", "city",
    "close", "example", "night", "real", "life", "few", "stop", "open", "seem",
    "together", "next", "white", "children", "begin", "got", "walk", "picture",
    "earth", "father", "light", "country", "school", "tree", "keep", "story",
    "food", "sun", "four", "eye", "last", "door", "cut", "done", "table", "hard",
    "room", "book", "sea", "draw", "left", "late", "run", "close", "color", "body",
    "music", "girl", "song", "family", "book", "river", "car", "morning", "eat",
];
